### ISSUE TITLE
Should bitfields work in enums?

### ISSUE THREAD

**Issue by litherum** [gpuweb/WSL#257]
In C++ programs, it's pretty common to write

```WHLSL
enum FoodsILike {
    IDontLikeFood = 0,
    Pizza = 1,
    Pasta = 2,
    Pastries = 4
    BrusselSprouts = 8,
}
...
FoodsILike theFoods = FoodsILike(7);
```

We should pick either
A. The above is supported, and `switch` statements that include every case in an enum still need a default case
B. The above case is not supported, and either traps or clamps (e.g. zero-fills)

**Comment by RobinMorisset** [comment]
I was planning to make the above not supported: in order to make the default case not mandatory in switches I even added a check in the semantics when doing a load that could race of an enum, to clamp the value back to one of the values enumerated in the enum.

Do you want us to support the above pattern?
