### ISSUE TITLE
consider namespaces for WHLSL

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#271]
If WHLSL is going to live a long time, I think it should support namespaces.  Namespaces are fundamental to good modularity.

After 30 years, it seems odd to still have to write things like NSArray.
How many people know or care that the NS is for NeXTStep?

A case in point, the usability and proliferation of Perl improved massively when Perl5 shipped with namespace support.

**Comment by kungfooman** [comment]
Or maybe start using TypeScript? VS:Code could help alot with day-to-day coding and refactoring (it shows all errors etc. while coding in editor, can mass rename files/classes/attributes/types etc. and update all other files)

Going even one step further: AssemblyScript... the static subset of TypeScript would compile directly to WebAssembly: https://github.com/AssemblyScript/assemblyscript (I would wait a bit with this one, because AssemblyScript first needs to mature a bit more, but could be quite interesting (small size + fast code))

**Comment by dneto0** [comment]
The community group is already at consensus that some derivative of HLSL is desirable for what most developers will use as a shader language because HLSL has massive mindshare and existing content.

**Comment by dneto0** [comment]
> If WHLSL is going to live a long time, I think it should support namespaces. Namespaces are fundamental to good modularity.

I had forgotten that:
- HLSL already reserves "namespace" as a keyword
- DXC for targeting SPIR-V for Vulkan already supports proper namespaces

**Comment by kainino0x** [comment]
@kungfooman This is a language for compiling and running on a GPU; not a browser language. The hardware constraints are vastly different and there's no way we could run anything JavaScript-like. It's theoretically possible to use something similar to WebAssembly, but it would be a huge project to link those two ecosystems (WASM and GPU) and add GPU operations and execution semantics to WASM - even bigger than WHLSL, I think, and not worth doing right now.

**Comment by kungfooman** [comment]
@kainino0x Sorry, I thought he was asking about namespaces for the JavaScript code.

**Comment by kainino0x** [comment]
Ah, np.
