### ISSUE TITLE
Is there a maximum token length? Particularly for identifiers

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#292]
The grammar allows arbitrarily long identifiers.

The test suite will run a finite set of tests, and so it will only test up to a maximum length.  Should we enshrine that limit somewhere so both implementations and users work to the same limit?

Traditionally the most sensitive tokens are at the integration points: things like a shader entry point name.  (Think "creat" in Unix, which was shortened to work with linkers used at the time.)

Other tokens with unbounded length include numeric literals, but those cases can be contained on semantic grounds (e.g. no reason to have a super long integer because it blows value limits.)

**Comment by litherum** [comment]
Generally, on the Web platform, limits like these aren't standardized. Each browser has things like arbitrary DOM node depth maximums and DOM node count maximums, and those aren't represented in standards documents. Programs can contain an arbitrary number of statements and expressions so limiting token length alone doesn't solve the harder problem of limiting complexity of the program.

Given the fact that all WHLSL programs will be passed through a compiler before delivered to a driver, we won't have to worry about driver bugs in this area since the outputted variable names will not be the same as the (arbitrarily long) inputted variable names.

It's slightly unfortunate for programmers to have to worry about length requirements of their variable names as they write their code.

**Comment by kainino0x** [comment]
If the token max is implementation dependent, programmers still might have to worry about it. It sounds like you want to spec the token length to be unlimited? (up to OOM?)

**Comment by kainino0x** [comment]
Should there be a minimum maximum token length in the spec?

**Comment by litherum** [comment]
A minimum is a good idea.

If we wanted to get into the business of standardizing things like token length limits, we should also probably standardize all the other arbitrary limits that real shipping implementations will have to have, like number of types / functions / expressions / statements / etc. Looking back on these kinds of limits in other parts of Web browsers, these are the kinds of limits that change over time arbitrarily as we change the performance characteristics of the browser.

**Comment by litherum** [comment]
Looks like the JavaScript spec doesn't describe token length limits.

**Comment by litherum** [comment]
SPIR-V [doesn't describe](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpName) token length limits (in the OpName instruction).

**Comment by litherum** [comment]
See also: https://github.com/gpuweb/WHLSL/issues/232
